//go:build go1.22

// Package test_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package test_server

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AgrirouterOauthPRODScopes = "agrirouterOauthPROD.Scopes"
	AgrirouterOauthQAScopes   = "agrirouterOauthQA.Scopes"
)

// Defines values for EndpointCapabilityDirection.
const (
	RECEIVE     EndpointCapabilityDirection = "RECEIVE"
	SEND        EndpointCapabilityDirection = "SEND"
	SENDRECEIVE EndpointCapabilityDirection = "SEND_RECEIVE"
)

// Defines values for EndpointType.
const (
	CommunicationUnit        EndpointType = "communication_unit"
	FarmingSoftware          EndpointType = "farming_software"
	TelemetryPlatform        EndpointType = "telemetry_platform"
	VirtualCommunicationUnit EndpointType = "virtual_communication_unit"
)

// Endpoint defines model for Endpoint.
type Endpoint struct {
	ApplicationId     openapi_types.UUID   `json:"application_id"`
	Capabilities      []EndpointCapability `json:"capabilities"`
	EndpointType      EndpointType         `json:"endpoint_type"`
	ExternalId        string               `json:"external_id"`
	Id                openapi_types.UUID   `json:"id"`
	SoftwareVersionId openapi_types.UUID   `json:"software_version_id"`

	// TenantId The tenant ID of the endpoint
	TenantId string `json:"tenant_id"`
}

// EndpointCapability defines model for EndpointCapability.
type EndpointCapability struct {
	Direction EndpointCapabilityDirection `json:"direction"`

	// MessageType The message type that the endpoint can send or receive.
	// See available types here:
	// https://docs.agrirouter.com/agrirouter-interface-documentation/latest/tmt/overview.html
	MessageType string `json:"message_type"`
}

// EndpointCapabilityDirection defines model for EndpointCapability.Direction.
type EndpointCapabilityDirection string

// EndpointSubscription defines model for EndpointSubscription.
type EndpointSubscription struct {
	// MessageType The message type that the endpoint is subscribed to.
	// See available types here:
	// https://docs.agrirouter.com/agrirouter-interface-documentation/latest/tmt/overview.html
	MessageType string `json:"message_type"`
}

// EndpointType defines model for EndpointType.
type EndpointType string

// PutEndpointRequest defines model for PutEndpointRequest.
type PutEndpointRequest struct {
	// ApplicationId The ID of the application that owns the endpoint
	ApplicationId openapi_types.UUID `json:"application_id"`

	// Capabilities The effective capabilities of the endpoint, must be subset of the capabilities of software version.
	Capabilities []EndpointCapability `json:"capabilities"`
	EndpointType EndpointType         `json:"endpoint_type"`

	// SoftwareVersionId The ID of the software version that owns the endpoint
	SoftwareVersionId openapi_types.UUID     `json:"software_version_id"`
	Subscriptions     []EndpointSubscription `json:"subscriptions"`
}

// XAgrirouterTenantId defines model for x-agrirouter-tenant-id.
type XAgrirouterTenantId = openapi_types.UUID

// PutEndpointParams defines parameters for PutEndpoint.
type PutEndpointParams struct {
	// XAgrirouterTenantId The farmer's tenant ID in relation to which communication is done.
	XAgrirouterTenantId XAgrirouterTenantId `json:"x-agrirouter-tenant-id"`
}

// SendMessagesParams defines parameters for SendMessages.
type SendMessagesParams struct {
	// ContentLength The size of the complete payload in bytes.
	// This is used to determine if the payload needs to be
	// split into chunks and how.
	ContentLength int64 `json:"content-length"`

	// XAgrirouterIsPublish If set to true, the message will be sent as a published message
	// and any endpoints that are subscribed to the message type
	// would be able to receive it, provided other conditions for routing are met.
	XAgrirouterIsPublish bool `json:"x-agrirouter-is-publish"`

	// XAgrirouterDirectRecipients Comma-separated list of agrirouter endpoint IDs of the direct recipients.
	// Allows specifying direct recipients of the message, which
	// could receive it even if they are not subscribed to the message type.
	XAgrirouterDirectRecipients *[]openapi_types.UUID `json:"x-agrirouter-direct-recipients,omitempty"`

	// XAgrirouterSentTimestamp Client side timestamp of sending the data.
	XAgrirouterSentTimestamp time.Time `json:"x-agrirouter-sent-timestamp"`

	// XAgrirouterEndpointId The agrirouter endpoint ID of the sender.
	// This is the ID of the endpoint that is sending the message.
	XAgrirouterEndpointId openapi_types.UUID `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterTeamsetContextId A teamset is a set of connected machines that work and move together
	// and are connected to the same (virtual) communication unit.
	// The machines in the teamset are typically connected physically and
	// informationally (for example via ISOBUS).
	XAgrirouterTeamsetContextId *string `json:"x-agrirouter-teamset-context-id,omitempty"`

	// XAgrirouterMessageType Message type of the sent data. See available types here:
	// https://docs.agrirouter.com/agrirouter-interface-documentation/latest/tmt/overview.html
	XAgrirouterMessageType string `json:"x-agrirouter-message-type"`

	// XAgrirouterTenantId The farmer's tenant ID in relation to which communication is done.
	XAgrirouterTenantId XAgrirouterTenantId `json:"x-agrirouter-tenant-id"`

	// XAgrirouterContextId Application side identifier of the sent data.
	// agrirouter will use this to generate application message id
	// and also will pass it on as chunk context id in case if the payload
	// had to be split into several messages.
	XAgrirouterContextId string `json:"x-agrirouter-context-id"`

	// XAgrirouterFilename Optional name of the file that is attached to messages as metadata.
	XAgrirouterFilename *string `json:"x-agrirouter-filename,omitempty"`
}

// PutEndpointJSONRequestBody defines body for PutEndpoint for application/json ContentType.
type PutEndpointJSONRequestBody = PutEndpointRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create or update endpoint
	// (PUT /endpoints/{externalId})
	PutEndpoint(w http.ResponseWriter, r *http.Request, externalId string, params PutEndpointParams)
	// Receive messages from agrirouter outbox
	// (GET /messages)
	ReceiveMessages(w http.ResponseWriter, r *http.Request)
	// Send one or several messages to agrirouter inbox
	// (POST /messages)
	SendMessages(w http.ResponseWriter, r *http.Request, params SendMessagesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PutEndpoint operation middleware
func (siw *ServerInterfaceWrapper) PutEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "externalId" -------------
	var externalId string

	err = runtime.BindStyledParameterWithOptions("simple", "externalId", r.PathValue("externalId"), &externalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "externalId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgrirouterOauthQAScopes, []string{"endpoints:manage"})

	ctx = context.WithValue(ctx, AgrirouterOauthPRODScopes, []string{"endpoints:manage"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PutEndpointParams

	headers := r.Header

	// ------------- Required header parameter "x-agrirouter-tenant-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-tenant-id")]; found {
		var XAgrirouterTenantId XAgrirouterTenantId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-tenant-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-tenant-id", valueList[0], &XAgrirouterTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-tenant-id", Err: err})
			return
		}

		params.XAgrirouterTenantId = XAgrirouterTenantId

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-tenant-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-tenant-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEndpoint(w, r, externalId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveMessages operation middleware
func (siw *ServerInterfaceWrapper) ReceiveMessages(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgrirouterOauthQAScopes, []string{})

	ctx = context.WithValue(ctx, AgrirouterOauthPRODScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveMessages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessages operation middleware
func (siw *ServerInterfaceWrapper) SendMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgrirouterOauthQAScopes, []string{})

	ctx = context.WithValue(ctx, AgrirouterOauthPRODScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SendMessagesParams

	headers := r.Header

	// ------------- Required header parameter "content-length" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("content-length")]; found {
		var ContentLength int64
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "content-length", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "content-length", valueList[0], &ContentLength, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "content-length", Err: err})
			return
		}

		params.ContentLength = ContentLength

	} else {
		err := fmt.Errorf("Header parameter content-length is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "content-length", Err: err})
		return
	}

	// ------------- Required header parameter "x-agrirouter-is-publish" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-is-publish")]; found {
		var XAgrirouterIsPublish bool
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-is-publish", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-is-publish", valueList[0], &XAgrirouterIsPublish, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-is-publish", Err: err})
			return
		}

		params.XAgrirouterIsPublish = XAgrirouterIsPublish

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-is-publish is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-is-publish", Err: err})
		return
	}

	// ------------- Optional header parameter "x-agrirouter-direct-recipients" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-direct-recipients")]; found {
		var XAgrirouterDirectRecipients []openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-direct-recipients", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-direct-recipients", valueList[0], &XAgrirouterDirectRecipients, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-direct-recipients", Err: err})
			return
		}

		params.XAgrirouterDirectRecipients = &XAgrirouterDirectRecipients

	}

	// ------------- Required header parameter "x-agrirouter-sent-timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-sent-timestamp")]; found {
		var XAgrirouterSentTimestamp time.Time
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-sent-timestamp", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-sent-timestamp", valueList[0], &XAgrirouterSentTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-sent-timestamp", Err: err})
			return
		}

		params.XAgrirouterSentTimestamp = XAgrirouterSentTimestamp

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-sent-timestamp is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-sent-timestamp", Err: err})
		return
	}

	// ------------- Required header parameter "x-agrirouter-endpoint-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-endpoint-id")]; found {
		var XAgrirouterEndpointId openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-endpoint-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-endpoint-id", valueList[0], &XAgrirouterEndpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-endpoint-id", Err: err})
			return
		}

		params.XAgrirouterEndpointId = XAgrirouterEndpointId

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-endpoint-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-endpoint-id", Err: err})
		return
	}

	// ------------- Optional header parameter "x-agrirouter-teamset-context-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-teamset-context-id")]; found {
		var XAgrirouterTeamsetContextId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-teamset-context-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-teamset-context-id", valueList[0], &XAgrirouterTeamsetContextId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-teamset-context-id", Err: err})
			return
		}

		params.XAgrirouterTeamsetContextId = &XAgrirouterTeamsetContextId

	}

	// ------------- Required header parameter "x-agrirouter-message-type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-message-type")]; found {
		var XAgrirouterMessageType string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-message-type", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-message-type", valueList[0], &XAgrirouterMessageType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-message-type", Err: err})
			return
		}

		params.XAgrirouterMessageType = XAgrirouterMessageType

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-message-type is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-message-type", Err: err})
		return
	}

	// ------------- Required header parameter "x-agrirouter-tenant-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-tenant-id")]; found {
		var XAgrirouterTenantId XAgrirouterTenantId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-tenant-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-tenant-id", valueList[0], &XAgrirouterTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-tenant-id", Err: err})
			return
		}

		params.XAgrirouterTenantId = XAgrirouterTenantId

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-tenant-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-tenant-id", Err: err})
		return
	}

	// ------------- Required header parameter "x-agrirouter-context-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-context-id")]; found {
		var XAgrirouterContextId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-context-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-context-id", valueList[0], &XAgrirouterContextId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-context-id", Err: err})
			return
		}

		params.XAgrirouterContextId = XAgrirouterContextId

	} else {
		err := fmt.Errorf("Header parameter x-agrirouter-context-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-agrirouter-context-id", Err: err})
		return
	}

	// ------------- Optional header parameter "x-agrirouter-filename" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-agrirouter-filename")]; found {
		var XAgrirouterFilename string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-agrirouter-filename", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-agrirouter-filename", valueList[0], &XAgrirouterFilename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-agrirouter-filename", Err: err})
			return
		}

		params.XAgrirouterFilename = &XAgrirouterFilename

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("PUT "+options.BaseURL+"/endpoints/{externalId}", wrapper.PutEndpoint)
	m.HandleFunc("GET "+options.BaseURL+"/messages", wrapper.ReceiveMessages)
	m.HandleFunc("POST "+options.BaseURL+"/messages", wrapper.SendMessages)

	return m
}

type PutEndpointRequestObject struct {
	ExternalId string `json:"externalId"`
	Params     PutEndpointParams
	Body       *PutEndpointJSONRequestBody
}

type PutEndpointResponseObject interface {
	VisitPutEndpointResponse(w http.ResponseWriter) error
}

type PutEndpoint200JSONResponse Endpoint

func (response PutEndpoint200JSONResponse) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutEndpoint201JSONResponse Endpoint

func (response PutEndpoint201JSONResponse) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PutEndpoint400Response struct {
}

func (response PutEndpoint400Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutEndpoint401Response struct {
}

func (response PutEndpoint401Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutEndpoint403Response struct {
}

func (response PutEndpoint403Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type PutEndpoint500Response struct {
}

func (response PutEndpoint500Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PutEndpoint502Response struct {
}

func (response PutEndpoint502Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(502)
	return nil
}

type PutEndpoint503Response struct {
}

func (response PutEndpoint503Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type PutEndpoint504Response struct {
}

func (response PutEndpoint504Response) VisitPutEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(504)
	return nil
}

type ReceiveMessagesRequestObject struct {
}

type ReceiveMessagesResponseObject interface {
	VisitReceiveMessagesResponse(w http.ResponseWriter) error
}

type ReceiveMessages200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ReceiveMessages200TexteventStreamResponse) VisitReceiveMessagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ReceiveMessages400Response struct {
}

func (response ReceiveMessages400Response) VisitReceiveMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ReceiveMessages401Response struct {
}

func (response ReceiveMessages401Response) VisitReceiveMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ReceiveMessages403Response struct {
}

func (response ReceiveMessages403Response) VisitReceiveMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type ReceiveMessages500Response struct {
}

func (response ReceiveMessages500Response) VisitReceiveMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type SendMessagesRequestObject struct {
	Params SendMessagesParams
	Body   io.Reader
}

type SendMessagesResponseObject interface {
	VisitSendMessagesResponse(w http.ResponseWriter) error
}

type SendMessages200Response struct {
}

func (response SendMessages200Response) VisitSendMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SendMessages400Response struct {
}

func (response SendMessages400Response) VisitSendMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type SendMessages401Response struct {
}

func (response SendMessages401Response) VisitSendMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SendMessages403Response struct {
}

func (response SendMessages403Response) VisitSendMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type SendMessages500Response struct {
}

func (response SendMessages500Response) VisitSendMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create or update endpoint
	// (PUT /endpoints/{externalId})
	PutEndpoint(ctx context.Context, request PutEndpointRequestObject) (PutEndpointResponseObject, error)
	// Receive messages from agrirouter outbox
	// (GET /messages)
	ReceiveMessages(ctx context.Context, request ReceiveMessagesRequestObject) (ReceiveMessagesResponseObject, error)
	// Send one or several messages to agrirouter inbox
	// (POST /messages)
	SendMessages(ctx context.Context, request SendMessagesRequestObject) (SendMessagesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PutEndpoint operation middleware
func (sh *strictHandler) PutEndpoint(w http.ResponseWriter, r *http.Request, externalId string, params PutEndpointParams) {
	var request PutEndpointRequestObject

	request.ExternalId = externalId
	request.Params = params

	var body PutEndpointJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutEndpoint(ctx, request.(PutEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutEndpointResponseObject); ok {
		if err := validResponse.VisitPutEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveMessages operation middleware
func (sh *strictHandler) ReceiveMessages(w http.ResponseWriter, r *http.Request) {
	var request ReceiveMessagesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveMessages(ctx, request.(ReceiveMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveMessagesResponseObject); ok {
		if err := validResponse.VisitReceiveMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendMessages operation middleware
func (sh *strictHandler) SendMessages(w http.ResponseWriter, r *http.Request, params SendMessagesParams) {
	var request SendMessagesRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendMessages(ctx, request.(SendMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendMessagesResponseObject); ok {
		if err := validResponse.VisitSendMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
